### ISSUE TITLE
Versions 1.3.x fabric crash the server

### ISSUE THREAD

**Issue by Manw107** [StickyPiston-development/CreateCobblestone#10]
Every version of the mod since the 1.3.0 version crashes my fabric server.
Here's the log with only the create, the fabric api and the create cobblestone
```
[17:50:41] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.0
[17:50:41] [main/INFO]: Loading 90 mods:
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- forgeconfigapiport 8.0.0
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_tags 3.0
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	- createcobblestone 1.3.2+fabric-1.20.1-38
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.16.0
	   \-- mixinextras 0.4.0
	- java 21
	- minecraft 1.20.1
	- porting_lib 2.3.4+1.20.1
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |-- porting_lib_asm 2.3.4+1.20.1
	   |-- porting_lib_attributes 2.3.4+1.20.1
	   |-- porting_lib_base 2.3.4+1.20.1
	   |-- porting_lib_blocks 2.3.4+1.20.1
	   |-- porting_lib_brewing 2.3.4+1.20.1
	   |-- porting_lib_chunk_loading 2.3.4+1.20.1
	   |-- porting_lib_client_events 2.3.4+1.20.1
	   |-- porting_lib_common 2.3.4+1.20.1
	   |-- porting_lib_config 2.3.4+1.20.1
	   |-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_data 2.3.4+1.20.1
	   |-- porting_lib_entity 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |-- porting_lib_fluids 2.3.4+1.20.1
	   |-- porting_lib_gametest 2.3.4+1.20.1
	   |-- porting_lib_gui_utils 2.3.4+1.20.1
	   |-- porting_lib_items 2.3.4+1.20.1
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |-- porting_lib_level_events 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |-- porting_lib_model_builders 2.3.4+1.20.1
	   |-- porting_lib_model_generators 2.3.4+1.20.1
	   |-- porting_lib_model_loader 2.3.4+1.20.1
	   |-- porting_lib_model_materials 2.3.4+1.20.1
	   |-- porting_lib_models 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |-- porting_lib_obj_loader 2.3.4+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
	   |-- porting_lib_registries 2.3.4+1.20.1
	   |-- porting_lib_tool_actions 2.3.4+1.20.1
	   |-- porting_lib_transfer 2.3.4+1.20.1
	   |-- porting_lib_utility 2.3.4+1.20.1
	   \-- reach-entity-attributes 2.4.0
[17:50:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/ubuntu/minecraft/sbovvata/libraries/net/fabricmc/sponge-mixin/0.15.0+mixin.0.8.7/sponge-mixin-0.15.0+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[17:50:41] [main/INFO]: Compatibility level set to JAVA_17
[17:50:42] [main/WARN]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
[17:50:42] [main/WARN]: @Mixin target net.minecraft.class_906 was not found porting_lib_tool_actions.mixins.json:FishingHookRendererMixin from mod porting_lib_tool_actions
[17:50:42] [main/WARN]: Error loading class: net/minecraft/class_481 (java.lang.ClassNotFoundException: net/minecraft/class_481)
[17:50:42] [main/WARN]: @Mixin target net.minecraft.class_481 was not found porting_lib_items.mixins.json:client.CreativeModeInventoryScreenMixin from mod porting_lib_items
[17:50:42] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[17:50:42] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[17:50:42] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.0).
[17:50:44] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on porting_lib_entity.mixins.json:common.LivingEntityMixin from mod porting_lib_entity::handler$zoa000$porting_lib_entity$port_lib$onFinishUsing exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[17:50:52] [main/INFO]: Create cobblestone initializing! Create version: 0.5.1f on platform: Fabric
[17:50:52] [main/WARN]: Configuration file ./config/createcobblestone-common.toml is not correct. Correcting
[17:50:52] [main/WARN]: Incorrect key common was corrected from null to its default, SimpleCommentedConfig:{}. 
[17:50:52] [main/WARN]: Incorrect key common.generatorStress was corrected from null to its default, 8. 
[17:50:52] [main/WARN]: Incorrect key common.generatorRatio was corrected from null to its default, 8.0. 
[17:50:52] [main/WARN]: Incorrect key common.maxGeneratorStorage was corrected from null to its default, 256. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled was corrected from null to its default, SimpleCommentedConfig:{}. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled.cobblestoneGeneratorEnabled was corrected from null to its default, true. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled.basaltGeneratorEnabled was corrected from null to its default, true. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled.stoneGeneratorEnabled was corrected from null to its default, true. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled.limestoneGeneratorEnabled was corrected from null to its default, true. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled.scoriaGeneratorEnabled was corrected from null to its default, true. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled.deepslateGeneratorEnabled was corrected from null to its default, false. 
[17:50:52] [main/WARN]: Incorrect key common.generatorsEnabled.cobbledDeepslateGeneratorEnabled was corrected from null to its default, false. 
[17:50:52] [main/INFO]: Registering blocks for Create cobblestone
[17:50:52] [main/INFO]: Registering blockEntities for Create cobblestone
[17:50:52] [main/INFO]: Create cobblestone is accessing Porting Lib on a Fabric server!
[17:50:52] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createcobblestone'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.0-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_1792$class_1793 net.minecraft.class_1792$class_1793.arch$tab(net.minecraft.class_5321)'
	at net.createcobblestone.index.Blocks.lambda$init$3(Blocks.java:84) ~[createcobblestone-1.3.2+fabric-1.20.1-38.jar:?]
	at com.tterrag.registrate.util.nullness.NonNullFunction.lambda$andThen$0(NonNullFunction.java:14) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.builders.ItemBuilder.createEntry(ItemBuilder.java:260) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.builders.ItemBuilder.createEntry(ItemBuilder.java:40) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.fabric.Lazy.get(Lazy.java:17) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:121) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:217) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:189) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:13) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:188) ~[registrate-fabric-1.3.62-MC1.20.1-ee112783731be492.jar:?]
	at net.createcobblestone.fabric.CreateCobblestoneFabric.onInitialize(CreateCobblestoneFabric.java:18) ~[createcobblestone-1.3.2+fabric-1.20.1-38.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
	... 7 more
```

**Comment by MrStickyPiston** [comment]
Have you installed architectury?

Edit for clearance: architectury API adds that method to minecraft. (archITECTURY:tab)

**Comment by Manw107** [comment]
No I didn't. Now it works thank you

**Comment by MrStickyPiston** [comment]
No problem.
