### ISSUE TITLE
Caused by 0: java.lang.NoClassDefFoundError: dev/architectury/platform/Platform 

### ISSUE THREAD

**Issue by MattRidge** [StickyPiston-development/CreateCobblestone#25]
I am not sure why this is going on, but I am now getting an error when attempting to run the CreateCobblestone on 1.20.1

also attached the file itself so if there are more things you need:
[crash-2024-11-30_00.52.45-fml.txt](https://github.com/user-attachments/files/17964402/crash-2024-11-30_00.52.45-fml.txt)

```
`Caused by 0: java.lang.NoClassDefFoundError: dev/architectury/platform/Platform
		at net.createcobblestone.index.Network.init(Network.java:22) ~[createcobblestone-1.4.1+forge-1.20.1-73.jar%23222!/:?] {re:classloading}
		at net.createcobblestone.CreateCobblestoneMod.init(CreateCobblestoneMod.java:21) ~[createcobblestone-1.4.1+forge-1.20.1-73.jar%23222!/:?] {re:mixin,re:classloading}
		at net.createcobblestone.forge.CreateCobblestoneForge.<init>(CreateCobblestoneForge.java:45) ~[createcobblestone-1.4.1+forge-1.20.1-73.jar%23222!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.20.1-47.3.12.jar%23238!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.12.jar%23237!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Mod File: /C:/Users/PapaBear/AppData/Roaming/ModrinthApp/profiles/test/mods/createcobblestone-1.4.1+forge-1.20.1-73.jar
	Failure message: Create cobblestone (createcobblestone) has failed to load correctly
		java.lang.NoClassDefFoundError: dev/architectury/platform/Platform
	Mod Version: 1.4.1+forge-1.20.1-73
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: dev.architectury.platform.Platform
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at net.createcobblestone.index.Network.init(Network.java:22) ~[createcobblestone-1.4.1+forge-1.20.1-73.jar%23222!/:?] {re:classloading}
	at net.createcobblestone.CreateCobblestoneMod.init(CreateCobblestoneMod.java:21) ~[createcobblestone-1.4.1+forge-1.20.1-73.jar%23222!/:?] {re:mixin,re:classloading}
	at net.createcobblestone.forge.CreateCobblestoneForge.<init>(CreateCobblestoneForge.java:45) ~[createcobblestone-1.4.1+forge-1.20.1-73.jar%23222!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.20.1-47.3.12.jar%23238!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.12.jar%23237!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

`
```

**Comment by MrStickyPiston** [comment]
Please install the architectury api
