### ISSUE TITLE
incompatibility

### ISSUE THREAD

**Issue by xcmohamedxx** [StickyPiston-development/CreateCobblestone#28]
when i used it whith fabric create it asked me to use a version compatible with create 0.5.1-j-build.1631+mc1.20.1 which i couldnt find

**Comment by MrStickyPiston** [comment]
Please try out the beta version: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/12138568941, or use an older create version

**Comment by Tehemo** [comment]
beta version unfortunately don't work

**Comment by MrStickyPiston** [comment]
> beta version unfortunately don't work

"Don't work" is very vague, please explain what did not work and send logs

**Comment by Tehemo** [comment]
```
[00:00:01] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.9
[00:00:01] [main/WARN]: Mod resolution failed
[00:00:01] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE createcobblestone 1.4.3-beta+fabric-1.20.1-75 {depends create @ [0.5.1-j-build.1609+mc1.20.1]}, ROOT_FORCELOAD_SINGLE createcobblestone 1.4.3-beta+fabric-1.20.1-75]
[00:00:01] [main/INFO]: Reason: [HARD_DEP createcobblestone 1.4.3-beta+fabric-1.20.1-75 {depends create @ [0.5.1-j-build.1609+mc1.20.1]}]
[00:00:01] [main/INFO]: Fix: add [], remove [], replace [[create 0.5.1-j-build.1631+mc1.20.1] -> add:create 0.5.1-j-build.1609+mc1.20.1 ([[0.5.1-j-build.1609+mc1.20.1,0.5.1-j-build.1609+mc1.20.1]])]
[00:00:01] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-j-build.1631+mc1.20.1 with version 0.5.1-j-build.1609+mc1.20.1.
More details:
	 - Mod 'Create Cobblestone' (createcobblestone) 1.4.3-beta+fabric-1.20.1-75 requires version 0.5.1-j-build.1609+mc1.20.1 of mod 'Create' (create), but only the wrong version is present: 0.5.1-j-build.1631+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]

```

version incompatible

**Comment by Shulej** [comment]
in `fabric.mod.json`->`depends`->`create` change `"${create_version}"` to `">=${create_version"` (this is for the dev)

**Comment by MrStickyPiston** [comment]
I am trying to fix this, for some reason the minecraft mappings dont work as intended atm so every build fails. After that is fixed, this will be the next thing im looking at.

**Comment by MrStickyPiston** [comment]
Fixed the build process, thanks @Shulej for the version fix and pull request.

Test build, please try it out: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/12469885624

**Comment by MrStickyPiston** [comment]
Changed it to say up to version 5.2 is supported to avoid breakage

Both fabric and forge: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/12485316243

**Comment by MrStickyPiston** [comment]
# Create Cobblestone 1.4.3-beta

updated the following dependencies:
- fabric_loader_version = 0.16.9
- fabric_api_version = 0.92.2+1.20.1
- create_fabric_version = 0.5.1-j-build.1609+mc1.20.1
- create_forge_version = 0.5.1.j-55
- flywheel_forge_version = 0.6.11-13

newer create versions are also supported now

Fabric: https://modrinth.com/mod/create-cobblestone/version/1.4.3-beta+fabric-1.20.1-85
Forge: https://modrinth.com/mod/create-cobblestone/version/1.4.3-beta+forge-1.20.1-85
