### ISSUE TITLE
Placing a generator using a schematticannon crashes a server.

### ISSUE THREAD

**Issue by StijnArts** [StickyPiston-development/CreateCobblestone#3]
Placing a generator using a schematticannon crashes a server.
`net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bng000$carpet$modifiedRunLoop(MinecraftServer.java:19442) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant net.createcobblestone.util.GeneratorType.
	at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at net.createcobblestone.util.GeneratorType.valueOf(GeneratorType.java:14) ~[createcobblestone-1.2.0+fabric-1.20.1-22.jar:?]
	at net.createcobblestone.blocks.CobblestoneGeneratorBlockEntity.read(CobblestoneGeneratorBlockEntity.java:50) ~[createcobblestone-1.2.0+fabric-1.20.1-22.jar:?]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntity.method_11014(SmartBlockEntity.java:119) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.utility.BlockHelper.placeSchematicBlock(BlockHelper.java:306) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.cannon.LaunchedItem$ForBlockState.place(LaunchedItem.java:129) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.cannon.LaunchedItem.update(LaunchedItem.java:63) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tickFlyingBlocks(SchematicannonBlockEntity.java:641) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tick(SchematicannonBlockEntity.java:281) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at net.minecraft.class_2818$class_5563.redirect$bnj000$carpet$checkProcessBEs(class_2818.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 6 more
`

**Comment by MrStickyPiston** [comment]
could you send me the schematic?

**Comment by StijnArts** [comment]
Sure! Also, Ive noticed that it only seems to happen when it places a cobblestone generator. Maybe its because the placed block doesnt have an enum assigned to it? Though I cant say for sure.

Honestly any schematic which places a cobblestone generator seems to cause a crash, but I can send you the schematic later today
________________________________

**Comment by MrStickyPiston** [comment]
You mean it doesnt crash with the other generators? Also, can you try if you can replicate it on the latest version?

**Comment by StijnArts** [comment]
Ive had this bug on 1.2.0, has it been updated since? And yeah I don't think it crashes with the other ones

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MrStickyPiston** [comment]
Yes, 1.3 just came out and has a lot of backend changes, including forge support. Could you please remove the outlook ad?

**Comment by MrStickyPiston** [comment]
I found the issue.

Create schematicannon places a fully nbt-less block, while the standard block always stores the type at default.

this is the code for readin the data:
```java
@Override
    protected void read(CompoundTag compound, boolean clientPacket) {
        super.read(compound, clientPacket);

        //CreateCobblestoneMod.LOGGER.error("Reading: " + compound.getAsString());
        this.type = GeneratorType.valueOf(compound.getString("type"));
    }
 ```
 
 with no data existing, it tries to parse "GeneratorType. "
 
 I will probally fix this in a few days, because will be fairly busy.

**Comment by MrStickyPiston** [comment]
got it working, needs some testing too. 
test build can be downloaded at the actions: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/9635484906
https://github.com/StickyPiston-development/CreateCobblestone/assets/97804691/6824286f-b703-4424-93dc-d8f0ea83a943

**Comment by StijnArts** [comment]
Thank you! Ill test it out tomorrow

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MrStickyPiston** [comment]
Here you go! (for forge, neoforge, fabric and quilt.
https://modrinth.com/mod/create-cobblestone/version/1.3.1+forge-1.20.1-36
https://modrinth.com/mod/create-cobblestone/version/1.3.1+fabric-1.20.1-36

**Comment by Legomountain14** [comment]
Here's a similar issue I'm having on 1.21.1.
https://mclo.gs/4lMBgWx#L22
